/**
 * OAuth provider abstraction — the contract every login provider must satisfy.
 *
 * Adding a new provider (e.g. Google, Apple, WeChat) means:
 *   1. Implement this interface in `lib/auth/providers/<provider>.ts`.
 *   2. Register it in `lib/auth/providers/index.ts` (PROVIDERS map).
 *   3. Add the corresponding OAuth env vars (see `.dev.vars.example`).
 * The API routes, JWT layer, user store, and UI all consume this interface
 * — they never touch provider-specific SDKs — so no other code needs to
 * change when a new provider is added.
 */

/**
 * Provider identifier.
 *
 * When adding a new provider, extend this union first — TypeScript will then
 * force every switch/registry to acknowledge the new provider.
 */
export type ProviderId = "github";
// Future: | "google" | "apple" | "wechat";

/**
 * Provider-agnostic user profile shape.
 *
 * All providers must normalise their API responses into this structure so
 * downstream code (user store, JWT, UI) is provider-independent.
 */
export interface NormalizedProfile {
  /** Which provider issued this profile. */
  provider: ProviderId;
  /** Stable per-provider user identifier (e.g. GitHub numeric id). */
  providerUserId: string;
  /** Login handle within the provider (e.g. GitHub `login`). */
  username: string;
  /** Human-readable display name (falls back to username). */
  displayName: string;
  /** Absolute URL to the user's avatar image, if any. */
  avatarUrl: string | null;
  /** Verified email address, if the provider exposes one. */
  email: string | null;
}

/**
 * OAuth authorize-URL parameters.
 *
 * The `state` value is opaque to the provider — it is generated by
 * `lib/auth/state.ts`, stored in an HTTP-only cookie, and echoed back to
 * `/api/auth/<provider>/callback` for CSRF protection.
 */
export interface AuthorizeUrlParams {
  state: string;
  /**
   * Absolute redirect URI that will receive the callback.
   * Must match the URI registered on the provider's OAuth app.
   */
  redirectUri: string;
}

/**
 * Result of a successful `code` → `access_token` exchange.
 *
 * Providers may return richer payloads (refresh tokens, id tokens, etc.);
 * they belong in provider-specific extensions rather than this base shape.
 */
export interface TokenResponse {
  accessToken: string;
  tokenType: string;
  scope: string | null;
}

/**
 * Runtime configuration a provider needs at construction time.
 *
 * Passed in explicitly (rather than read from `process.env`) so the provider
 * layer stays pure and testable — the registry in `providers/index.ts` is
 * the sole place that pulls values off the env.
 */
export interface ProviderConfig {
  clientId: string;
  clientSecret: string;
}

/**
 * The uniform contract every OAuth provider implementation exposes.
 *
 * Keep this small: routes should be able to complete a login using only the
 * methods listed here. Anything provider-specific (e.g. GitHub's email
 * endpoint fallback) is an internal implementation detail.
 */
export interface OAuthProvider {
  /** Provider identifier — must match its key in the PROVIDERS registry. */
  readonly id: ProviderId;

  /** Human-readable name shown in the login page (e.g. "GitHub"). */
  readonly displayName: string;

  /**
   * Build the URL the browser should be redirected to in order to start the
   * OAuth flow. The provider is responsible for appending its own required
   * query parameters (scope, response_type, etc.).
   */
  getAuthorizeUrl(params: AuthorizeUrlParams): string;

  /**
   * Exchange the short-lived `code` returned to the callback URL for an
   * access token. Should throw on non-2xx responses so the callback route
   * can respond with a clear error.
   */
  exchangeCodeForToken(code: string, redirectUri: string): Promise<TokenResponse>;

  /**
   * Fetch the authenticated user's profile using the access token and
   * normalise it to `NormalizedProfile`.
   */
  fetchUserProfile(accessToken: string): Promise<NormalizedProfile>;
}
